### ISSUE TITLE
pbcopy: command not found; which -s invalid option

### ISSUE THREAD

**Issue by agarrubio** [backus/ai.sh#3]
For everythng to work in Ubuntu I had to do these:
```
alias ai=`/bin/readlink -f /path/to/ai.sh`
```
Make sure you have xclip or install it. Then, in ai.sh, change this line:
```
pbcopy < "$completion_temp_file"
```
to:
```
xclip -sel clip < "$completion_temp_file"
```
In ai.sh change this line:
```
which -s "$1" > /dev/null
```
to:
```
which "$1" > /dev/null
```
Then I was able to use this great software!

**Comment by ChristophSiegenthaler** [comment]
Same here, thanks for the code backus and for the tips, agarrubio

**Comment by backus** [comment]
Thank you for sharing that! I don't necessarily plan to generalize this to outside of macOS since I only use mac, but I'm glad you got it working and I'll add a link in the README that people should check out this issue if they want to adapt the project. I'm glad the rest of it worked well on a different OS. I'm never quite sure how much is coupled to my system.

**Comment by backus** [comment]
@agarrubio @ChristophSiegenthaler you both might also benefit from this small tweak: https://github.com/backus/ai.sh/pull/4
